### ISSUE TITLE
CMake issue

### ISSUE THREAD

**Issue by ChenZiyu** [jvm-profiling-tools/perf-map-agent#49]
Hi
I have ran cmake. Some error happened. Do you have any idea?

-- JNI_INCLUDE_DIRS=/usr/lib/jvm/java-7-openjdk-amd64/include;/usr/lib/jvm/java-7-openjdk-amd64/include;/usr/lib/jvm/java-7-openjdk-amd64/include
-- JNI_LIBRARIES=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjawt.so;/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
-- JAVA_INCLUDE_PATH=/usr/lib/jvm/java-7-openjdk-amd64/include
-- JAVA_INCLUDE_PATH2=/usr/lib/jvm/java-7-openjdk-amd64/include
CMake Error at /usr/share/cmake-2.8/Modules/UseJava.cmake:269 (string):
  string sub-command LENGTH requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:30 (add_jar)

-- Configuring incomplete, errors occurred!

**Comment by ChenZiyu** [comment]
cmake version 2.8.9 

java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

**Comment by ChenZiyu** [comment]
I already solve it. the cmake version is too old

**Comment by jrudolph** [comment]
Cool, which cmake version did solve it? We could require it in the config.
