### ISSUE TITLE
perf-map-agent as jvmti agent on start

### ISSUE THREAD

**Issue by RainM** [jvm-profiling-tools/perf-map-agent#68]
Hi,

I tried to use perf-map-agent as pure JVMTI agent via -agentlib argument. But the current implementation doesn't have Agent_OnLoad method.

So, does it worth to implement Agen_OnLoad function (I'm ready to do it)? If so, should I handle a situation when compiled method was abandoned (is it possible to handle these situations?)?

--Sergey

**Comment by jrudolph** [comment]
Hi @RainM. See #27 for a previous discussion on a similar topic.

**Comment by RainM** [comment]
Thanks, @jrudolph. #27 has points for next experiments.

**Comment by RainM** [comment]
Should I close this issue as duplicate since we have #27 with the same issue?

**Comment by jrudolph** [comment]
Yep, that's close this one.
